# Titanic Survival Prediction 

Please check https://www.kaggle.com/c/titanic/data 

# Loading data from CSV

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

# Show first 5 records

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# Show list of column names

In [4]:
df.keys()

Index([u'PassengerId', u'Survived', u'Pclass', u'Name', u'Sex', u'Age',
       u'SibSp', u'Parch', u'Ticket', u'Fare', u'Cabin', u'Embarked'],
      dtype='object')

# Drop some unnecessary columns

In [5]:
df2=df.drop(['Name','PassengerId','Cabin','Ticket'],1)

In [6]:
df2.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

# For column 'Sex', create another numeric column (sexc)

In [7]:
code={'female':0,'male':1}
for k,i in df2.iterrows():
    df2.loc[k,"sexc"]=code[i['Sex']]

In [8]:
df2.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  sexc
0         0       3    male  22.0      1      0   7.2500        S   1.0
1         1       1  female  38.0      1      0  71.2833        C   0.0
2         1       3  female  26.0      0      0   7.9250        S   0.0
3         1       1  female  35.0      1      0  53.1000        S   0.0
4         0       3    male  35.0      0      0   8.0500        S   1.0

# Count number of records of each category

In [9]:
df2["Embarked"].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

# For column 'Embarked', create another numeric column (embarkedc)

In [10]:

code={'C':0,'Q':1, 'S':2}
for k,i in df2.iterrows():
    if i['Embarked']==i['Embarked']:
        df2.loc[k,"embarkedc"]=code[i['Embarked']]

In [11]:
df2.head(10)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  sexc  \
0         0       3    male  22.0      1      0   7.2500        S   1.0   
1         1       1  female  38.0      1      0  71.2833        C   0.0   
2         1       3  female  26.0      0      0   7.9250        S   0.0   
3         1       1  female  35.0      1      0  53.1000        S   0.0   
4         0       3    male  35.0      0      0   8.0500        S   1.0   
5         0       3    male   NaN      0      0   8.4583        Q   1.0   
6         0       1    male  54.0      0      0  51.8625        S   1.0   
7         0       3    male   2.0      3      1  21.0750        S   1.0   
8         1       3  female  27.0      0      2  11.1333        S   0.0   
9         1       2  female  14.0      1      0  30.0708        C   0.0   

   embarkedc  
0        2.0  
1        0.0  
2        2.0  
3        2.0  
4        2.0  
5        1.0  
6        2.0  
7        2.0  
8        2.0  
9        0.0

In [12]:
#remove the original column
df3=df2.drop(['Sex','Embarked'],1)

# Drop every NaN row

In [13]:
df4=df3.dropna(axis=0)
df4.head(10)

Survived  Pclass   Age  SibSp  Parch     Fare  sexc  embarkedc
0          0       3  22.0      1      0   7.2500   1.0        2.0
1          1       1  38.0      1      0  71.2833   0.0        0.0
2          1       3  26.0      0      0   7.9250   0.0        2.0
3          1       1  35.0      1      0  53.1000   0.0        2.0
4          0       3  35.0      0      0   8.0500   1.0        2.0
6          0       1  54.0      0      0  51.8625   1.0        2.0
7          0       3   2.0      3      1  21.0750   1.0        2.0
8          1       3  27.0      0      2  11.1333   0.0        2.0
9          1       2  14.0      1      0  30.0708   0.0        0.0
10         1       3   4.0      1      1  16.7000   0.0        2.0

# Alternative approuch--drop every NaN row using Masking

In [14]:
df5=df3[ df3['Age'].notnull() ]
df5.head()

Survived  Pclass   Age  SibSp  Parch     Fare  sexc  embarkedc
0         0       3  22.0      1      0   7.2500   1.0        2.0
1         1       1  38.0      1      0  71.2833   0.0        0.0
2         1       3  26.0      0      0   7.9250   0.0        2.0
3         1       1  35.0      1      0  53.1000   0.0        2.0
4         0       3  35.0      0      0   8.0500   1.0        2.0

# Convert Dataframe to numpy array for traning

In [15]:
X=df4.as_matrix([df4.columns[1:]])

In [16]:
y=df4.as_matrix(["Survived"])

In [17]:
y.shape

(712L, 1L)

In [18]:
y=y.reshape(-1)

In [19]:
y.shape

(712L,)

In [20]:
X.shape

(712L, 7L)

# Traning

In [21]:
from sklearn.ensemble import ExtraTreesClassifier

In [22]:
forest = ExtraTreesClassifier(n_estimators=250,random_state=0)

In [23]:
forest.fit(X,y)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=250, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

# Prediction

In [24]:
forest.predict([3,22.0,1,0,7.2500,1.0,2.0])

array([0], dtype=int64)

In [25]:
forest.predict([1,38.0,1,0,71.2833,0.0,0.0])

array([1], dtype=int64)

In [26]:
#Dummy Jack 
#Pclass, Age, SibSp, Parch, Fare, sexc, embarkedc
forest.predict([3,25.0,0,0,0.0,1,1])

array([0], dtype=int64)

In [27]:
#Dummy Rose
forest.predict([1,23.0,0,1,50.0,0,1])

array([1], dtype=int64)

## end of note